apiVersion: v1
kind: Service
metadata:
  name: music-external
  namespace: music1
  labels:
    app: web
    tier: frontend
  annotations:
    "service.beta.kubernetes.io/aws-load-balancer-internal": "0.0.0.0/0"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: web
    tier: frontend
