apiVersion: v1
kind: Service
metadata:
  name: music-external
  namespace: music1
  labels:
    app: web
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: web
    tier: frontend
