apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: music-ingress
  namespace: music1
  annotations: {}
spec:
  tls:
  - hosts:
    - music.pks.hulk.pvd.pez.pivotal.io
    secretName: test-secret
  rules:
  - host: music.pks.hulk.pvd.pez.pivotal.io
    http:
      paths:
      - path: /*
        backend:
          serviceName: music-service
          servicePort: 8080
